### PR TITLE
Implemented logit bias

### PR DESCRIPTION
**Pull request by Tyrest**
This PR addresses #352. Not completely sure if this is the right place to implement it.

### CODE REVIEW

**Comment by DhruvaBansal00** [comment]
Is implementing this for huggingface within the scope of this PR? Or is this only for supporting biased generation with OpenAI?

**Comment by Tyrest** [comment]
Currently this is implemented only how OpenAI takes it (as a model parameter)

**Review by DhruvaBansal00 — APPROVED** [review]
LGTM!

**Comment by rishabh-bhargava** [comment]
Need to make sure that adding `logit_bias` in tasks other than classification / entity matching throw an error.

**Pull request merged**
