### PR TITLE
Autolabel config cli

### PR DESCRIPTION
**Pull request by Tyrest**
## Adds an Autolabel CLI to reduce friction for new users! #456 
Here's what a sample use case might look like for the `company` dataset

First execute the `create-config` command...

Screenshot 2023-07-17 at 2 58 48 PM

Then, execute `plan` to make sure everything looks good...

Screenshot 2023-07-17 at 3 03 06 PM

Finally, execute `run` to start the labeling task!

Screenshot 2023-07-17 at 3 06 44 PM

### Help pages

General

Screenshot 2023-07-17 at 2 59 55 PM

plan

Screenshot 2023-07-17 at 3 00 17 PM

run

Screenshot 2023-07-17 at 3 00 30 PM

create-config

Screenshot 2023-07-17 at 3 00 44 PM

### CODE REVIEW

**Comment by Tyrest** [comment]
### New Automatic Config Creation
The goal for this is to have the user do as little as possible to get to a working config.
Screenshot 2023-07-24 at 11 50 46 AM

### New Help Page for Config Command
Screenshot 2023-07-24 at 11 52 44 AM

**Comment by nihit** [comment]
Changes from the meeting w/ @Tyrest @rajasbansal :

Autolabel config: 
1. "wizard" mode is the default -- it is an interactive multi-step workflow to arrive at a final config
2. "non wizard" mode will be invoked with "autolabel config init". It outputs a template/starter config with all the valid keys, and values being descriptions of what value should the user put there. E.g.:

```
{
    "task_name": "[TODO] Enter task name",
    "task_type": "...",
    "dataset": {
        "label_column": "...",
        "delimiter": "..."
    },
    "model": {...},
    "prompt": {...}
```

**Comment by Tyrest** [comment]
Added placeholder values for values that we cannot infer as shown below.
 
Screenshot 2023-07-25 at 4 57 49 PM

The new default for `autolabel config` is the wizard:
Screenshot 2023-07-25 at 4 59 24 PM

Updated the help page
Screenshot 2023-07-25 at 5 05 16 PM

**Review by nihit — APPROVED** [review]
lgtm! 
do we need to add any dependencies for the CLI app ?

**Pull request merged**
