### PR TITLE
added individual retrying for failed batches

### PR DESCRIPTION
**Pull request by Tyrest**
If the batch fails, simply splits the batch into the individual prompts and then retries them.

### CODE REVIEW

**Comment by Tyrest** [comment]
This is currently done synchronously.

**Comment by Tyrest** [comment]
#433

**Comment by yadavsahil197** [comment]
Does it make sense to move the retry logic into a wrapper method within the base model class?

**Review by yadavsahil197 — APPROVED** [review]
LGTM

**Pull request merged**
