### PR TITLE
Fix open api key error handling

### LINKED ISSUE #421: [Bug]: Confusing error message when OpenAI API Key is missing
**Describe the bug**
When the OpenAI API key is missing, we see the following error message:

```
File ~/.pyenv/versions/3.8.13/envs/refuel-main/lib/python3.8/site-packages/langchain/load/serializable.py:64, in Serializable.__init__(self, **kwargs)
     63 def __init__(self, **kwargs: Any) -> None:
---> 64     super().__init__(**kwargs)
     65     self._lc_kwargs = kwargs

File ~/.pyenv/versions/3.8.13/envs/refuel-main/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```

This is an error from `langchain`, but `autolabel` doesn't allow passing `openai_api_key` as a named parameter anywhere. 

**To Reproduce**
Call `agent.plan` for a config that uses an OpenAI model without providing the API key as an env variable. 

**Expected behavior**
We should throw an error that simply says that the user should add the API key as an environment variable and not that it should be a named parameter.

### PR DESCRIPTION
**Pull request by chirag-manwani**
Fixes #421 

This PR adds a check for the presence of the OPENAI_API_KEY environment variable. Also it fixes a typo in the config.json in the README (and a couple of linting changes).

### CODE REVIEW

**Comment by chirag-manwani** [comment]
I considered wrapping the code between [line-91](https://github.com/refuel-ai/autolabel/blob/e73342bebb2936d2aeb1200d6b07da24f2e3dbbc/src/autolabel/models/openai.py#L91)  and [line-99](https://github.com/refuel-ai/autolabel/blob/e73342bebb2936d2aeb1200d6b07da24f2e3dbbc/src/autolabel/models/openai.py#L99) inside a try/except block and checking for the Validation error message for a missing API key(I am not completely sure if there is a better way), but in that case I thought the code should handle all sorts of Validation errors and not just this one. However since there can be many such Validation Errors, [where one Validation Error object may contain more than one error](https://github.com/pydantic/pydantic/blob/15d5e0b0abdd79fd63d34954e8dacaa9f1a255f8/pydantic/v1/error_wrappers.py#L58C31-L58C40), it seemed like a better idea to check for the API key separately. 

This was the code I thought would work but not sure how to handle other validation errors. 
```python
try:
    if self._engine == "chat":
        self.model_params = {**self.DEFAULT_PARAMS_CHAT_ENGINE, **model_params}
        self.llm = ChatOpenAI(model_name=self.model_name, **self.model_params)
    else:
        self.model_params = {
            **self.DEFAULT_PARAMS_COMPLETION_ENGINE,
            **model_params,
        }
        self.llm = OpenAI(model_name=self.model_name, **self.model_params)
except ValidationError as err:
    if err.__str__().find("Did not find openai_api_key") != -1:
        raise ValueError("OPENAI_API_KEY environment variable not set") from None
    else:
        raise err from None
```

**Comment by chirag-manwani** [comment]
This is what it looks like. 

```python
from autolabel import LabelingAgent
agent = LabelingAgent(config='downloads/config.json')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/packages/venv/env-1/lib/python3.11/site-packages/autolabel/labeler.py", line 49, in __init__
    self.llm: BaseModel = ModelFactory.from_config(self.config, cache=self.cache)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/packages/venv/env-1/lib/python3.11/site-packages/autolabel/models/__init__.py", line 58, in from_config
    return model_cls(config, cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/packages/venv/env-1/lib/python3.11/site-packages/autolabel/models/openai.py", line 103, in __init__
    raise ValueError("OPENAI_API_KEY environment variable not set") from None
ValueError: OPENAI_API_KEY environment variable not set
```

**Review by nihit — APPROVED** [review]
lgtm! thanks @chirag-manwani for this fix

**Comment by nihit** [comment]
If you haven't already, also consider joining our Discord: https://discord.gg/fweVnRx6CU

**Pull request merged**
